### ISSUE TITLE
Updating Farseek from 1.0.6 to 1.0.7 crashes other mods. SMP server only.

### ISSUE THREAD

**Issue by Oxosorrel** [delvr/Farseek#1]
Using both Forge 1403, or 1395, I receive the following error on my SMP server. Mod list in the crash report linked below. This arrangement of mods works fine single player.

It crashes Rikmuld's camping mod,
https://gist.github.com/Oxosorrel/64e9d1c8cb33b2a45ae6 

This doesn't appear isolated, it crashes in a very similar way for pnuematicraft and someone else reported it to Pneumaticraft here:

here.https://github.com/MineMaarten/PneumaticCraft/issues/458 I had the same error as this one when I had pneumaticraft and farseek 1.0.7 installed.

Rolling farseek back to 1.0.6 corrects both the camping mod and pnuematicraft crashes.

**Comment by Amaxter** [comment]
I have this issue as well.

**Comment by delvr** [comment]
Acknowledged. This is caused by an overaggressive fix intended for the Biomes'O'Plenty server crash. I flagged 1.0.7 as Alpha on CurseForge so 1.0.6 will remain the default download on the forum. The next release will fix the BOP bug without these regressions with other mods. Meanwhile unless you need 1.0.7 to use BOP, please stick to 1.0.6 for now. Thanks!
