### ISSUE TITLE
Crash on latest spongeforge

### ISSUE THREAD

**Issue by Tencao** [delvr/Farseek#43]
Original issue with all relevant information - https://github.com/SpongePowered/SpongeForge/issues/2331

**Comment by Tencao** [comment]
Any update on a fix for this issue?

**Comment by delvr** [comment]
Hey Tencao, sorry for the delay on this one.

I assumed that the crash was due to Sponge changing the name of an internal method Farseek was using (as described in the linked Sponge issue), but I can't find any record in the Sponge source of that name actually changing. In fact, I was unable to reproduce the crash using the version of Sponge you were using. I tried adding Biomes'O'Plenty since it shows up in your stacktrace - still no crash.

Could you try again with only SpongeForge and Farseek/Streams/Repose and maybe BOP, and tell me if it still crashes? If not, we'll have to work to isolate the mod that triggers this.

**Comment by Tencao** [comment]
I'll try again later today and report back any findings

**Comment by Rautherdir** [comment]
While looking into this issue myself, I found that this is most likely a duplicate of https://github.com/Ordinastie/MalisisCore/issues/151
Adding MalisisCore to the list of mods mentioned above causes this issue to appear.

**Comment by delvr** [comment]
Thanks @Rautherdir  for the update! I tested and confirmed that the crash only happens when MalisisCore is present. I'll close this issue; if the MalisisCore devs fix the issue on their end and then Farseek still crashes with their new version we'll re-open this.
