### ISSUE TITLE
Crash game (1.12.2)

### ISSUE THREAD

**Issue by SeagalKru** [delvr/Farseek#56]
[crash-2020-01-29_16.53.50-server.txt](https://github.com/delvr/Farseek/files/4128379/crash-2020-01-29_16.53.50-server.txt)

**Comment by TheDeviantCrafter** [comment]
I've been running into the same issue. It happens when teleporting to a biome with a Nature's Compass. Trying to teleport to the same location on the same world after a restart triggers the same crash.

My pack has a *lot* of biome and worldgen mods. Looking at @SeagalKru's crash we both have Streams, Farseek, Traverse, and Dynamic Trees. That may be a clue.

Crash log: https://paste.dimdev.org/dihonukopi.mccrash

latest.log: https://gist.github.com/TheDeviantCrafter/c21c09cd099505efec33eeca2814ac4b

My pack has quite a few customized biome spawn weights, so a specific seed won't be useful without the pack. I plan to release an experimental build of the pack in a couple of days. When that happens I'll update this issue with a modpack, world folder, and coordinates that reliably trigger the crash so you can troubleshoot on your end.

**Comment by TheDeviantCrafter** [comment]
Update: Using a Nature's Compass to teleport to the location triggered a crash. Flying their normally did *not.* It may require Nature's Compass specifically.

**Comment by RepoDraghon** [comment]
https://paste.dimdev.org/tigucevava.mccrash

Here's my crash report... it sites 3 mods to blame, this being one...

[Minecraft 1.12.2 Error.txt](https://github.com/delvr/Farseek/files/4253004/Minecraft.1.12.2.Error.txt)

**Comment by delvr** [comment]
Farseek 2.5 might fix this, could you please give it a try? Thanks.

**Comment by RepoDraghon** [comment]
seems to be fixed or at least it's not naming this mod as before :) ty

**Comment by SeagalKru** [comment]
Ok.
Clossed.
:)

**Comment by EverSoul** [comment]
I updated to Farseek 2.5 and my modpack started crashing.

**Comment by delvr** [comment]
> 
> 
> I updated to Farseek 2.5 and my modpack started crashing.

Could you open a new issue and paste the crash log? Thanks!

**Comment by ProsperCraft** [comment]
Same issue with the crashing - 
https://github.com/delvr/Farseek/issues/60

I wish he had posted his crash logs so we could compare.
